/*********************************************************************************
*  WEB422 – Assignment 3
*  I declare that this assignment is my own work in accordance with Seneca Academic Policy.  
*  No part of this assignment has been copied manually or electronically from any other source
*  (including web sites) or distributed to other students.
* 
*  Name: Raghav Malhotra Student ID: 153547211 Date: 15/06/2023
*
*
********************************************************************************/ 

import useSWR from "swr";
import { useState, useEffect } from "react";
import { Inter } from "next/font/google";
import PageHeader from "@/components/PageHeader";
import Head from "next/head";
import { Pagination, Table } from "react-bootstrap";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  var [page, setPage] = useState(1);
  var [pageData, setPageData] = useState([]);
  const { data, error } = useSWR(`https://wild-teal-hermit-crab-tux.cyclic.app/api/trips?page=${page}&perPage=10`);

  useEffect(() => {
    if (data) {
      setPageData(data);
    }
  }, [data]);

  function previous(e){
    if (page > 1) setPage(page - 1);
  }
  function next(e){
    setPage(page + 1);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader
        title="Trips List"
        text="Full list of Citibike Trips."
        showCustomer={"true"}
        showSubscriber={"true"}
      />
      <Table striped bordered hover>
        <thead>
          <tr>
            <th>Bike ID</th>
            <th>Start Station</th>
            <th>End Station</th>
            <th>Duration</th>
          </tr>
        </thead>
        <tbody id="Subscriber">
          {pageData.map((trip) => (
            <tr
              key={trip._id}
              onClick={() => {
                router.push(`/trip/${trip._id}`);
              }}
            >
              <td id={trip.usertype}>{trip.bikeid}</td>
              <td id={trip.usertype}>{trip["start station name"]}</td>
              <td id={trip.usertype}>{trip["end station name"]}</td>
              <td id={trip.usertype}>{(trip.tripduration / 60).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </Table>
      <Pagination>
        <Pagination.Prev onClick={previous} />
        <Pagination.Item>{page}</Pagination.Item>
        <Pagination.Next onClick={next} />
      </Pagination>
    </>
  );
}